title: Meera Hahn
email: meerahahn@gatech.edu
description: Meera Hahn's Website

baseurl: "/test"
url: "https://meerahahn.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: ['_pages']

ga_id: UA-163181097-2
